services:
  printbot:
    build:
      context: .
      args:
        VERSION: "1.0.0"
    image: ghcr.io/zr0aces/printbot:1.0.0
    container_name: printbot
    restart: always
    devices:
      - /dev/usb/lp0:/dev/usb/lp0
    volumes:
      - /var/run/cups/cups.sock:/var/run/cups/cups.sock
    env_file:
      - .env
