services:
  printermasterbot:
    build: .
    image: printermasterbot
    container_name: printermasterbot
    restart: always
    devices:
      - /dev/usb/lp0:/dev/usb/lp0
    volumes:
      - /var/run/cups/cups.sock:/var/run/cups/cups.sock
    env_file:
      - .env
